#!/bin/bash

set -e

MODULE_DIR=$(realpath "$(dirname $0)")
MODULE=$(basename $MODULE_DIR)

bm-env nginx setup

pid=$(pm2 pid $MODULE)
if [[ $pid = "" || $pid = "0" ]]; then
    pm2 start $MODULE_DIR/config.json
else
    echo "$MODULE already started"
fi
