#!/bin/bash

set -e

BASE_DIR=$(realpath "$(dirname $0)")
CMD_DIR=$BASE_DIR/commands

source $BASE_DIR/profile.sh %>& /dev/null

command=$1

if [[ $command = "help" ]]; then
    echo "Help not written yet."

elif [ -f $CMD_DIR/$command ]; then
    bash $CMD_DIR/$command

elif [ -d $CMD_DIR/$command ]; then
    subcommand=$2
    subcommand_file=$CMD_DIR/$command/$subcommand

    if [ -f $CMD_DIR/$command/$subcommand ]; then
        bash $subcommand_file

    else
        echo "Unknown subcommand $command:$subcommand"

    fi

else
    echo "Unknown command $command"
    exit 1
    
fi